version: '3.8'
services:

    simulation-A1-L1:
        image: spikeinterface/mountainsort5-base:latest
        volumes:
        - ./app:/app
        - ./MEArec:/MEArec
        - K:/ke/sta/data/mearec/cell_models/A1/L1:/cell_models
        - K:/ke/sta/data/mearec/recordings/A1/L1:/output
        - ./logs:/logs
        environment:
        - LOGGING_DIR=/logs/
        - CELL_MODELS_DIR=/cell_models/
        - OUTPUT_DIR=/output/
        - REDO_TEMPLATES=1
        - REDO_RECORDINGS=1
        command: bash -c "pip install --upgrade pip && apt-get update && apt-get install -y build-essential && pip install MEArec/ && pip install -e app/ && python /app/source/main.py && exit 0"
        ports:
        - "8011:8000"