version: '3.8'
services:

    simulation-A1-L6:
        image: spikeinterface/mountainsort5-base:latest
        volumes:
        - ./app:/app
        - ./MEArec:/MEArec
        - K:/ke/sta/data/mearec/cell_models/A1/L6:/cell_models
        - K:/ke/sta/data/mearec/recordings/A1/L6:/output
        - ./logs:/logs
        environment:
        - LOGGING_DIR=/logs/
        - CELL_MODELS_DIR=/cell_models/
        - OUTPUT_DIR=/output/
        - REDO_TEMPLATES=0
        - REDO_RECORDINGS=1
        - REGION_NUM=6
        command: bash -c "pip install --upgrade pip && apt-get update && apt-get install -y build-essential && pip install -e MEArec/ && pip install -e app/ && python /app/source/main.py && exit 0"
        ports:
        - "8016:8000"
