drift_mode_speed: slow
drift_mode_probe: rigid
drift_fs: 100
non_rigid_gradient_mode: linear
non_rigid_linear_direction: 1
non_rigid_step_depth_boundary: null
non_rigid_step_factors: null
slow_drift_velocity: 5
slow_drift_amplitude: null
slow_drift_waveform: triangluar
fast_drift_period: 10
fast_drift_max_jump: 20
fast_drift_min_jump: 5
t_start_drift: null
t_end_drift: null
external_drift_vector_um: null
external_drift_times: null
external_drift_factors: null