drift_mode_speed: slow
drift_mode_probe: rigid
drift_fs: 1000
non_rigid_gradient_mode: linear
non_rigid_linear_direction: 1
non_rigid_step_depth_boundary: null
non_rigid_step_factors: null
slow_drift_velocity: 5
slow_drift_amplitude: 10
slow_drift_waveform: triangluar
fast_drift_period: 10
fast_drift_max_jump: null
fast_drift_min_jump: null
t_start_drift: 0
t_end_drift: 300
external_drift_vector_um: null
external_drift_times: null
external_drift_factors: null