apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f K:\ke\dev\2024-neuron-tracker-simulations\docker-compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: simulation-a1-l1
  name: simulation-a1-l1
spec:
  ports:
    - name: "8011"
      port: 8011
      targetPort: 8000
  selector:
    io.kompose.service: simulation-a1-l1
