apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f K:\ke\dev\2024-neuron-tracker-simulations\docker-compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: simulation-a1-l1
  name: simulation-a1-l1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: simulation-a1-l1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f K:\ke\dev\2024-neuron-tracker-simulations\docker-compose.yaml
        kompose.version: 1.33.0 (3ce457399)
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "10"
        gke-gcsfuse/cpu-request: 500m
      labels:
        io.kompose.network/2024-neuron-tracker-simulations-default: "true"
        io.kompose.service: simulation-a1-l1
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - args:
            - bash
            - -c
            - sleep 1000000
          env:
            - name: CELL_MODELS_DIR
              value: /bucket/mearec/cell_models/A1/L1
            - name: LOGGING_DIR
              value: /bucket/mearec/logs/A1/L1
            - name: OUTPUT_DIR
              value: /bucket/mearec/recordings/A1/L1
          image: gcr.io/neuron-tracker-simulation/mountainsort5-base:latest
          name: simulation-a1-l1
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /bucket
              name: gcs-fuse-csi-ephemeral
      serviceAccountName: neuron-tracker-sim-sa
      restartPolicy: Always
      volumes:
        - name: gcs-fuse-csi-ephemeral
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: neuron-tracker-simulation
              mountOptions: "implicit-dirs"
              gcsfuseLoggingSeverity: warning
