apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f K:\ke\dev\2024-neuron-tracker-simulations\docker-compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: simulation-a1-l23
  name: simulation-a1-l23
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: simulation-a1-l23
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f K:\ke\dev\2024-neuron-tracker-simulations\docker-compose.yaml
        kompose.version: 1.33.0 (3ce457399)
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "10"
        gke-gcsfuse/cpu-request: 500m
      labels:
        io.kompose.network/2024-neuron-tracker-simulations-default: "true"
        io.kompose.service: simulation-a1-l23
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - args:
            - bash
            - -c
            - echo ">>>>STARTING SIMULATION<<<<<" && pip install --upgrade pip && apt-get update && apt-get install -y build-essential && git clone https://github.com/olivershetler/neuron-tracker-simulation.git && pip install -e neuron-tracker-simulation/source && python /neuron-tracker-simulation/source/source/main_gcs.py && echo ">>>>FINISHED SIMULATION<<<<<"
          env:
            - name: CELL_MODELS_DIR
              value: mearec/cell_models/A1/L23
            - name: LOGGING_DIR
              value: mearec/logs/A1/L23
            - name: OUTPUT_DIR
              value: mearec/recordings/A1/L23
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/path/to/your/service-account-file.json"
          image: gcr.io/neuron-tracker-simulation/mountainsort5-base:latest
          name: simulation-a1-l23
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "8Gi"
            requests:
              cpu: "500m"
              memory: "500Mi"
      serviceAccountName: neuron-tracker-sim-sa
      restartPolicy: Always
