apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f K:\ke\dev\2024-neuron-tracker-simulations\docker-compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: simulation-a1-l1
  name: simulation-a1-l1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: simulation-a1-l1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f K:\ke\dev\2024-neuron-tracker-simulations\docker-compose.yaml
        kompose.version: 1.33.0 (3ce457399)
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "10"
        gke-gcsfuse/cpu-request: 500m
      labels:
        io.kompose.network/2024-neuron-tracker-simulations-default: "true"
        io.kompose.service: simulation-a1-l1
    spec:
      containers:
        - args:
            - bash
            - -c
            - echo ">>>>STARTING SIMULATION<<<<<" && pip install --upgrade pip && apt-get update && apt-get install -y build-essential && git clone https://github.com/olivershetler/neuron-tracker-simulation.git && pip install -e neuron-tracker-simulation/source && ls && python /neuron-tracker-simulation/source/source/main.py && echo ">>>>FINISHED SIMULATION<<<<<" && exit 0
          env:
            - name: CELL_MODELS_DIR
              value: /bucket/mearec/cell_models/A1/L1
            - name: LOGGING_DIR
              value: /bucket/logs/A1/L1
            - name: OUTPUT_DIR
              value: /bucket/output/A1/L1
          image: gcr.io/neuron-tracker-simulation/mountainsort5-base:latest
          name: simulation-a1-l1
          ports:
            - containerPort: 8000
              hostPort: 8011
              protocol: TCP
          volumeMounts:
            - mountPath: /bucket
              name: gcs-fuse-csi-ephemeral
      serviceAccountName: neuron-tracker-simulation-service-account
      restartPolicy: Always
      volumes:
        - name: gcs-fuse-csi-ephemeral
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: neuron-tracker-simulation
              mountOptions: "implicit-dirs"
              gcsfuseLoggingSeverity: warning
