apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcsfuse-storage-class
provisioner: gcsfuse.csi.storage.gke.io
parameters:
  bucketName: neuron-tracker-simulation
  gcsfuseLoggingSeverity: warning
  mountOptions: implicit-dirs
reclaimPolicy: Retain
volumeBindingMode: Immediate
